# Generated by Django 5.2.16 on 2026-07-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_is_active_remove_job_salary_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
